server:
  port: 9999
  context-path: /cmfz
spring:
  datasource:
    username: root
    password: 111
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml